<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>泛舟湖上成员信息检索</title>
	<!--接入extjs-->
	<link rel="stylesheet" type="text/css" href="../ext/resources/css/ext-all.css" />

	<script type="text/javascript" src="/ext/bootstrap.js"></script>
	<script type="text/javascript" src="/ext/locale/ext-lang-zh_CN.js"></script>
	<!--自定义js-->
	<script type="text/javascript" src="/myjs/index.js">
	</script>
	

	

</head>
<body>

</body>
</html>